name: EZDrop
author: Weediati
main: item.ezdrop.Main
version: 0.01_BETA
commands:
  drop:
    description: Pokazuje drop.
    aliases: [kamien, stone]
  turbodrop:
    description: turbodrop.
    aliases: [turbogracz, turboo]